---
# handlers file for roles/mariadb
- name: start mariadb server
  service:
   name: mariadb
   state: started
   enabled: yes
- name: restart mariadb server
  service:
   name: mariadb
   state: restarted
   enabled: yes
- name: stop mariadb server
  service: 
   name: mariadb
   state: stopped
